version: "3.8"
services:
  redis:
    image: redis:6.2-rc1
    network_mode: "host"
    restart: "unless-stopped"

  db:
    image: postgres:13.1
    network_mode: "host"
    restart: "unless-stopped"
    environment:
      - POSTGRES_PASSWORD=PGPASSWORD
